[package]
name = "rustkpi-hello"
version = "0.1.0"
authors = ["Johannes Lundberg <johalun0@gmail.com>"]

[dependencies]
kernel = { path = "../kmod-rustkpi/kernel" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
